openeuropa/oe_webtools

modules/oe_webtools_analytics/tests/src/Kernel/AnalyticsEventSubscriberServiceTest.php, modules/oe_webtools_analytics/tests/src/Kernel/ConfigurationTest.php
=> OPENEUROPA-715: Missing group added to tests.

.drone.yml, README.md, composer.json, docker-compose.yml
Update images on docker-compose and drone file.
- Changed: Images on docker-compose and drone file.
```sh
no commands
```
=> OPENEUROPA-582: Update images on docker-compose and drone file.

composer.json, grumphp.yml.dist
Update code-review to 0.3 and update grumphp.dist.yml so that we don't override default tasks
- Changed: Code review to version 0.3
=> OPENEUROPA-721: Update code-review and grump.yml.dist file.

behat.yml.dist, composer.json, modules/oe_webtools_analytics/modules/oe_webtools_analytics_rules/config/schema/webtools_analytics_rule.schema.yml, modules/oe_webtools_analytics/modules/oe_webtools_analytics_rules/oe_webtools_analytics_rules.info.yml, modules/oe_webtools_analytics/modules/oe_webtools_analytics_rules/oe_webtools_analytics_rules.links.action.yml, modules/oe_webtools_analytics/modules/oe_webtools_analytics_rules/oe_webtools_analytics_rules.links.menu.yml, modules/oe_webtools_analytics/modules/oe_webtools_analytics_rules/oe_webtools_analytics_rules.module, modules/oe_webtools_analytics/modules/oe_webtools_analytics_rules/oe_webtools_analytics_rules.services.yml, modules/oe_webtools_analytics/modules/oe_webtools_analytics_rules/src/Entity/WebtoolsAnalyticsRule.php, modules/oe_webtools_analytics/modules/oe_webtools_analytics_rules/src/Entity/WebtoolsAnalyticsRuleInterface.php, modules/oe_webtools_analytics/modules/oe_webtools_analytics_rules/src/EventSubscriber/WebtoolsAnalyticsEventSubscriber.php, modules/oe_webtools_analytics/modules/oe_webtools_analytics_rules/src/Form/WebtoolsAnalyticsRuleDeleteForm.php, modules/oe_webtools_analytics/modules/oe_webtools_analytics_rules/src/Form/WebtoolsAnalyticsRuleForm.php, modules/oe_webtools_analytics/modules/oe_webtools_analytics_rules/src/WebtoolsAnalyticsRuleListBuilder.php, modules/oe_webtools_analytics/modules/oe_webtools_analytics_rules/src/WebtoolsAnalyticsSiteSectionCacheContext.php, modules/oe_webtools_analytics/modules/oe_webtools_analytics_rules/tests/src/Functional/SectionRulesTest.php, runner.yml.dist, tests/Behat/WebtoolsAnalyticsConfigContext.php, tests/Behat/WebtoolsAnalyticsMinkContext.php, tests/features/site-section.feature
The Webtools analytics team needs to set the site section based on a regex by simple configuration.
- Added: Add config entities for section rules
=> OPENEUROPA-665: Add section rules to Webtool Analytics.

modules/oe_webtools_analytics/README.md, modules/oe_webtools_analytics/config/schema/oe_webtools_analytics.schema.yml, modules/oe_webtools_analytics/src/EventSubscriber/AnalyticsEventSubscriber.php, modules/oe_webtools_analytics/tests/src/Kernel/ConfigurationTest.php
The oe_webtools_analytics json snippet needs to include an instance parameter. 
- Added: Configuration option to add an instance parameter to the analytics json
=> OPENEUROPA-1465: Add instance parameter to webtools analytics

behat.yml.dist, tests/features/laco-widget.feature, tests/features/site-section.feature
=> OPENEUROPA-1522: Make sure we don't use Drupal paths in Behat scenarios.

behat.yml.dist, composer.json, modules/oe_webtools_cookie_consent/oe_webtools_cookie_consent.info.yml, modules/oe_webtools_cookie_consent/oe_webtools_cookie_consent.module, runner.yml.dist, tests/Behat/WebtoolsCookieConsentContext.php, tests/features/cookie-consent-kit.feature
Create OE Webtools cookie consent module which provides functionality related to cookie consent kit.
For now this module is empty and could be used later. Used for oe media module. 
- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:
```sh
```
=> OPENEUROPA-1590: Add OE Webtools cookie consent kit.

modules/oe_webtools_social_share/oe_webtools_social_share.info.yml
Fixes https://github.com/openeuropa/oe_webtools/issues/47
See also: https://github.com/openeuropa/oe_webtools/pull/41
=> Issue #47: Add oe_webtools dependency to oe_webtools_social_share.

modules/oe_webtools_laco_service/tests/src/Kernel/LacoServiceTest.php
=> OPENEUROPA-1874: Fixing tests.

modules/oe_webtools_analytics/README.md
Updated README to include instance config example.
- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:
```sh
```
=> Added instance to README.

composer.json
Fix behat test upgrading oe_media.
- Added:
- Changed: Composer.json
- Deprecated:
- Removed:
- Fixed:
- Security:
=> OPENEUROPA-1813: Fix behat test upgrading oe_media.

CHANGELOG.md
Create release 0.4.1.
- Added:
- Changed: ChangeLog.md
- Deprecated:
- Removed:
- Fixed:
- Security:
=> OPENEUROPA-1813: Create release 0.4.1.

composer.json
=> OPENEUROPA-1813: Upgrade to 8.7.

CHANGELOG.md
=> Update CHANGELOG.md for release 1.0.0.

composer.json
- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:
```sh
```
=> OPENEUROPA-1864: Fix dependencies from oe_media.

modules/oe_webtools_analytics/modules/oe_webtools_analytics_rules/README.md, modules/oe_webtools_analytics/modules/oe_webtools_analytics_rules/src/Entity/WebtoolsAnalyticsRule.php, tests/features/multilingual-aliases.feature, tests/features/site-section.feature
Use existing permission "administer webtools analytics" when using webtools' rules.
- Changed: Used permission.
=> OPENEUROPA-1901: Use permission administer webtools analytics.

.drone.yml
Remove permission related steps from drone.
- Changed: Remove permission related steps from drone.
=> OPENEUROPA-1897: Remove permission related steps from drone.

.drone.yml, behat.yml.dist, modules/oe_webtools_maps/oe_webtools_maps.behat.inc, runner.yml.dist, tests/features/oe-webtools-maps-step-definitions.feature, tests/fixtures/static_html/no_maps.html, tests/fixtures/static_html/one_map.html, tests/fixtures/static_html/two_maps.html
Add latest webtools location updates.
- Added: Add latest webtools location updates.
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:
```sh
```
=> OPENEUROPA-1835: Add latest webtools location updates.

modules/oe_webtools_cookie_consent/oe_webtools_cookie_consent.libraries.yml, tests/Behat/WebtoolsCookieConsentContext.php
=> OPENEUROPA-2084: Fix url of CCK.

CHANGELOG.md
Update the changelog for the release 1.2.1.
=> OPENEUROPA-1766: Update the changelog for the release 1.2.1.

modules/oe_webtools_geocoding/oe_webtools_geocoding.info.yml, modules/oe_webtools_laco_widget/oe_webtools_laco_widget.info.yml, modules/oe_webtools_maps/oe_webtools_maps.info.yml
Make the package consistent for all submodules.
- Changed:
Change the package name for the submodule to "OpenEuropa Webtools"
=> Issue #85: Make the package consistent for all submodules.

modules/oe_webtools_maps/oe_webtools_maps.behat.inc
Class name doesn't match filename; expected "class OeWebtoolsMapsSubContext".
See Issue #89
=> Issue #89: Fix PHPCS issue in master.

.drone.yml, behat.yml.dist, composer.json, modules/oe_webtools_analytics/modules/oe_webtools_analytics_rules/oe_webtools_analytics_rules.info.yml, modules/oe_webtools_analytics/modules/oe_webtools_analytics_rules/tests/src/Functional/SectionRulesTest.php, modules/oe_webtools_analytics/modules/oe_webtools_analytics_rules/tests/src/Kernel/AnalyticsRulesSubscriberTest.php, modules/oe_webtools_analytics/oe_webtools_analytics.info.yml, modules/oe_webtools_analytics/oe_webtools_analytics.module, modules/oe_webtools_analytics/tests/src/Functional/ConfigurationTest.php, modules/oe_webtools_globan/tests/src/Functional/ConfigurationTest.php, modules/oe_webtools_laco_widget/oe_webtools_laco_widget.info.yml, modules/oe_webtools_laco_widget/tests/src/Functional/LacoWidgetTest.php, modules/oe_webtools_maps/oe_webtools_maps.behat.inc, modules/oe_webtools_maps/oe_webtools_maps.info.yml, runner.yml.dist, tests/Behat/WebtoolsCookieConsentContext.php, tests/Behat/WebtoolsExtensionsContext.php, tests/Behat/WebtoolsExtentionsContext.php, tests/Behat/WebtoolsMapsContext.php, tests/features/analytics.feature, tests/features/cookie-consent-kit.feature, tests/features/global-banner.feature, tests/features/laco-widget.feature, tests/features/multilingual-aliases.feature, tests/features/oe-webtools-maps-step-definitions.feature, tests/features/site-section.feature, tests/src/Functional/SmartLoaderDependenciesTest.php
- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:
```sh
```
=> OPENEUROPA-1999: [oe_webtools] Improve test coverage for oe_webtools loader library.

README.md, composer.json
Update README for Webtools Maps requirements.
- Added: requirements in README for Webtools maps
- Removed: unnecessary requirement
=> OPENEUROPA-0000: Update README for Webtools Maps requirements.

.drone.yml, composer.json
Use PHP 7.2 in drone and docker image.
- Added: PHP 7.2 usage in docker-compose and drone.
=> OPENEUROPA-2258: Use PHP 7.2 in drone and docker image.

modules/oe_webtools_social_share/oe_webtools_social_share.module, modules/oe_webtools_social_share/src/Plugin/Block/SocialShareBlock.php, modules/oe_webtools_social_share/templates/oe-webtools-social-share.html.twig, modules/oe_webtools_social_share/tests/Kernel/SocialShareBlockTest.php
Add social share block template.
- Added: social share block template
=> OPENEUROPA-2558: Add social share block template.

README.md, composer.json
- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:
```sh
```
=> OPENEUROPA-2868: Add description about submodule in main README file.

CHANGELOG.md
Prepare release 1.6.0.
- Added:
- Changed: Update changelog for release 1.6.0
- Deprecated:
- Removed:
- Fixed:
- Security:
```sh
```
=> OPENEUROPA-0000: Prepare release 1.6.0.

modules/oe_webtools_europa_search/oe_webtools_europa_search.info.yml, modules/oe_webtools_europa_search/src/Plugin/Block/EuropaSearchBlock.php, modules/oe_webtools_europa_search/tests/src/Kernel/EuropaSearchBlockTest.php
- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:
```sh
```
=> OPENEUROPA-3278: Expose Europa Search as block.

CHANGELOG.md
- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:
```sh
```
=> Update CHANGELOG.md for 1.7.0 release.

composer.json, modules/oe_webtools_cookie_consent/README.md, modules/oe_webtools_cookie_consent/oe_webtools_cookie_consent.info.yml, modules/oe_webtools_cookie_consent/oe_webtools_cookie_consent.libraries.yml, modules/oe_webtools_cookie_consent/oe_webtools_cookie_consent.module, modules/oe_webtools_cookie_consent/oe_webtools_cookie_consent.post_update.php, tests/Behat/WebtoolsCookieConsentContext.php, tests/features/cookie-consent-kit.feature, tests/src/Functional/SmartLoaderDependenciesTest.php
- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:
```sh
```
=> EWPP-414: Update CCK module to use version 2.

CHANGELOG.md
- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:
```sh
```
=> Prepare release 1.10.0.

modules/oe_webtools_laco_service/src/Controller/LacoServiceController.php, modules/oe_webtools_laco_service/tests/src/Kernel/LacoServiceTest.php
The first commit shows the problem and the second fixes it.
=> EWPP-1648: Ensuring LACO works with mapped languages.

modules/oe_webtools_page_feedback/tests/src/Functional/PageFeedbackFormTest.php, modules/oe_webtools_page_feedback/tests/src/FunctionalJavascript/PageFeedbackAdminFormTest.php
- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:
```sh
```
=> EWPP-0000: Fixing broken page feedback form test.

modules/oe_webtools_social_share/translations/oe_webtools_social_share-uk.po, modules/oe_webtools_social_share/translations/oe_webtools_social_share-zh-hans.po
- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:
```sh
```
=> EWPP-2101: Add translation for chinese and ukrainian languages.

modules/oe_webtools_social_share/translations/oe_webtools_social_share-ru.po
- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:
```sh
```
=> EWPP-2125: Add translation for ru language.

modules/oe_webtools_media/src/Plugin/media/Source/Webtools.php, modules/oe_webtools_media/tests/src/FunctionalJavascript/MediaSourceWebtoolsTest.php
- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:
```sh
```
=> EWPP-2057: Add Qlik service for chart webtools media.

CHANGELOG.md
- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:
```sh
```
=> Prepare release 1.19.0.

modules/oe_webtools_media/src/Plugin/Validation/Constraint/WebtoolsMediaConstraintValidator.php, modules/oe_webtools_media/tests/src/FunctionalJavascript/MediaSourceWebtoolsTest.php
- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:
```sh
```
=> EWPP-2775: Adapt WebtoolsMediaConstraintValidator for opwidget service.

CHANGELOG.md
- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:
```sh
```
=> Prepare changelog for 1.23.0 release.

modules/oe_webtools_analytics/modules/oe_webtools_analytics_rules/src/EventSubscriber/AnalyticsRulesSubscriber.php, modules/oe_webtools_analytics/modules/oe_webtools_analytics_rules/src/RuleMatcher.php, modules/oe_webtools_analytics/src/AnalyticsEventInterface.php, modules/oe_webtools_analytics/src/CustomDimensions.php, modules/oe_webtools_analytics/src/CustomDimensionsInterface.php, modules/oe_webtools_analytics/src/Event/AnalyticsEvent.php, modules/oe_webtools_cookie_consent/oe_webtools_cookie_consent.module, modules/oe_webtools_media/src/Plugin/Validation/Constraint/WebtoolsMediaConstraintValidator.php
- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:
```sh
```
=> EWPP-3326: Add support of webtools custom dimensions.

tests/Behat/WebtoolsCookieConsentContext.php
- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:
```sh
```
=> EWPP-3345: Fix behat step for asserting CCK usage.

CHANGELOG.md
- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:
```sh
```
=> Prepare release 1.25.0.

.drone.yml, composer.json, docker-compose.yml, modules/oe_webtools_analytics/modules/oe_webtools_analytics_rules/oe_webtools_analytics_rules.info.yml, modules/oe_webtools_analytics/oe_webtools_analytics.info.yml, modules/oe_webtools_captcha/oe_webtools_captcha.info.yml, modules/oe_webtools_captcha/tests/modules/oe_webtools_captcha_mock/oe_webtools_captcha_mock.info.yml, modules/oe_webtools_cookie_consent/oe_webtools_cookie_consent.info.yml, modules/oe_webtools_etrans/oe_webtools_etrans.info.yml, modules/oe_webtools_europa_search/oe_webtools_europa_search.info.yml, modules/oe_webtools_geocoding/oe_webtools_geocoding.info.yml, modules/oe_webtools_globan/oe_webtools_globan.info.yml, modules/oe_webtools_laco_service/oe_webtools_laco_service.info.yml, modules/oe_webtools_laco_service/src/OeWebtoolsLacoServiceServiceProvider.php, modules/oe_webtools_laco_service/tests/modules/oe_webtools_laco_service_test/oe_webtools_laco_service_test.info.yml, modules/oe_webtools_laco_widget/oe_webtools_laco_widget.info.yml, modules/oe_webtools_maps/oe_webtools_maps.info.yml, modules/oe_webtools_media/oe_webtools_media.info.yml, modules/oe_webtools_media_wcloud_mock/oe_webtools_media_wcloud_mock.info.yml, modules/oe_webtools_page_feedback/oe_webtools_page_feedback.info.yml, modules/oe_webtools_social_share/modules/oe_webtools_social_share_demo/oe_webtools_social_share_demo.info.yml, modules/oe_webtools_social_share/oe_webtools_social_share.info.yml, modules/oe_webtools_social_share/src/Plugin/Block/SocialShareBlock.php, modules/oe_webtools_social_share/tests/Kernel/SocialShareBlockTest.php, modules/oe_webtools_wtag/oe_webtools_wtag.info.yml, oe_webtools.info.yml, tests/features/cookie-consent-kit.feature
- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:
```sh
```
=> EWPP-3797: Update SBKM to 2.0 version.

CHANGELOG.md
- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:
```sh
```
=> Prepare release 1.27.0

.drone.yml, modules/oe_webtools_captcha/config/install/oe_webtools_captcha.settings.yml, modules/oe_webtools_cookie_consent/oe_webtools_cookie_consent.module, modules/oe_webtools_cookie_consent/tests/src/Kernel/IframeFilterPluginKernelTest.php, modules/oe_webtools_media/src/Plugin/media/Source/Webtools.php, oe_webtools.libraries.yml, tests/fixtures/static_html/etrans_button.html, tests/fixtures/static_html/etrans_icon.html, tests/fixtures/static_html/etrans_link.html, tests/fixtures/static_html/one_map.html, tests/fixtures/static_html/two_maps.html, tests/src/Functional/SmartLoaderDependenciesTest.php
- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:
```sh
```
=> EWPP-4269: Replace hardcoded webtools url.

CHANGELOG.md
- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:
```sh
```
=> EWPP-0000: Update changelog.

.drone.yml
- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:
```sh
```
=> OEL-3033: Update to Drupal 10.3.

README.md, modules/oe_webtools_cookie_consent/README.md, modules/oe_webtools_cookie_consent/oe_webtools_cookie_consent.module, modules/oe_webtools_cookie_consent/tests/src/Kernel/IframeFilterPluginKernelTest.php, oe_webtools.module, tests/src/Functional/SmartLoaderDependenciesTest.php
- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:
```sh
```
=> EWPP-4267: Add override of smartload library in settings.php file.

.drone.yml, README.md, docker-compose.yml
- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:
```sh
```
=> EWPP-5461: Update sparql image in docker-compose.yml and for drone.yml.

.drone.yml, composer.json, modules/oe_webtools_analytics/modules/oe_webtools_analytics_rules/oe_webtools_analytics_rules.info.yml, modules/oe_webtools_analytics/modules/oe_webtools_analytics_rules/src/Entity/WebtoolsAnalyticsRule.php, modules/oe_webtools_analytics/modules/oe_webtools_analytics_rules/tests/src/Kernel/AnalyticsRulesSubscriberTest.php, modules/oe_webtools_analytics/oe_webtools_analytics.info.yml, modules/oe_webtools_captcha/oe_webtools_captcha.info.yml, modules/oe_webtools_captcha/tests/modules/oe_webtools_captcha_mock/oe_webtools_captcha_mock.info.yml, modules/oe_webtools_cookie_consent/oe_webtools_cookie_consent.info.yml, modules/oe_webtools_etrans/oe_webtools_etrans.info.yml, modules/oe_webtools_etrans/tests/src/Kernel/ETransBlockTest.php, modules/oe_webtools_europa_search/oe_webtools_europa_search.info.yml, modules/oe_webtools_geocoding/oe_webtools_geocoding.info.yml, modules/oe_webtools_globan/oe_webtools_globan.info.yml, modules/oe_webtools_globan/src/Form/WebtoolsGlobanSettingsForm.php, modules/oe_webtools_laco_service/oe_webtools_laco_service.info.yml, modules/oe_webtools_laco_service/tests/modules/oe_webtools_laco_service_test/oe_webtools_laco_service_test.info.yml, modules/oe_webtools_laco_widget/oe_webtools_laco_widget.info.yml, modules/oe_webtools_maps/oe_webtools_maps.info.yml, modules/oe_webtools_media/oe_webtools_media.info.yml, modules/oe_webtools_media_wcloud_mock/oe_webtools_media_wcloud_mock.info.yml, modules/oe_webtools_page_feedback/oe_webtools_page_feedback.info.yml, modules/oe_webtools_social_share/modules/oe_webtools_social_share_demo/oe_webtools_social_share_demo.info.yml, modules/oe_webtools_social_share/oe_webtools_social_share.info.yml, modules/oe_webtools_wtag/oe_webtools_wtag.info.yml, oe_webtools.info.yml, phpunit.xml.dist, tests/features/site-section.feature, tests/modules/oe_webtools_js_mock/oe_webtools_js_mock.info.yml, tests/src/Functional/SmartLoaderDependenciesTest.php
- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:
```sh
```
=> EWPP-4629: Support D11
